name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Deploy to Hugging Face Spaces
      uses: huggingface/github-action-deploy-spaces@main
      with:
        hf_token: ${{ secrets.HF_TOKEN }}
        
